[server]
[server.grpc]
addr = "localhost:4242"
[server.http]
addr = "localhost:4243"

[data]
[data.mongodb]
connection_string = "mongodb://localhost:27017"
database = "payment"
collection = "transactions"

[logger]
env = "dev"
